name: virtual_assistant
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dialogflow: ^0.1.0
  firebase_core: ^0.4.4+3
  fluttertoast: ^4.0.0
  firebase_auth: ^0.15.5+3
  google_sign_in: ^4.2.0
  flutter_facebook_login: ^3.0.0
  flutter_twitter_login: ^1.1.0
  translator: ^0.1.4
  flutter_tts: ^0.9.1
  firebase_ml_vision: ^0.9.3+8
  image_picker: ^0.6.4
  speech_to_text: ^2.0.1
  shared_preferences_settings: ^1.2.0 
  google_fonts: ^0.3.10
  share: ^0.6.3+6
  android_intent: ^0.3.6+1
  url_launcher: ^5.4.2
  flutter_webview_plugin: ^0.3.11

dev_dependencies:
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/virtual-assistant-htiehx-78c19d0cb278.json
    - img/ic_launcher.png
    - img/google.png
    - img/twitter.png
    - img/facebook.png
    - img/background.png