name: virtual_assistant
description: A virtual assistant Flutter project.

version: 1.0.3+3
 
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dialogflow: ^0.1.0
  firebase_core: ^0.4.4+3
  fluttertoast: ^4.0.0
  firebase_auth: ^0.16.0
  google_sign_in: ^4.2.0
  flutter_facebook_login: ^3.0.0
  flutter_twitter_login: ^1.1.0
  translator: ^0.1.4
  flutter_tts: ^1.2.0
  firebase_ml_vision: ^0.9.3+8
  image_picker: ^0.6.4
  speech_to_text: ^2.0.1
  shared_preferences_settings: ^1.2.0 
  google_fonts: ^1.1.0
  share: ^0.6.3+6
  android_intent: ^0.3.7
  url_launcher: ^5.4.2
  flutter_webview_plugin: ^0.3.11
  firebase_performance: ^0.3.1+8
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.3+3
  firebase_admob: ^0.9.3+2
  permission_handler: ^5.0.0+hotfix.3
  shared_preferences: ^0.5.6+3

flutter:
  uses-material-design: true
  assets:
    - assets/virtual-assistant-service-account.json
    - img/ic_launcher.png
    - img/google.png
    - img/twitter.png
    - img/facebook.png