name: virtual_assistant
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dialogflow: ^0.1.0
  firebase_core: ^0.4.0+9
  fluttertoast: ^4.0.0
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.5+3
  google_sign_in: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/virtual-assistant-htiehx-78c19d0cb278.json
    - img/ic_launcher.png
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700